version: 2
jobs:
  python_test:
    docker:
      - image: circleci/python:3.7
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_TOKEN      
    steps:
      - run: mkdir ~/repo
      - checkout:
          path: ~/repo/
      - run: virtualenv ~/repo/venv
      - run: echo "source ~/repo/venv/bin/activate" >> $BASH_ENV
      - run: pip install --upgrade pip
      - run: pip install 'tox==3.5.0'
      - run: pip install tox-venv
      - run: cd ~/repo && tox -v
workflows:
  version: 2
  build:
    jobs:
      - python_test
